import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Resumo",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
