import "./globals.css";
import { Russo_One } from "next/font/google";

import { Navbar } from "@/components/layouts/Navbar";
import { Aside } from "@/components/layouts/Aside";

const russoOne = Russo_One({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Amaril.io | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={russoOne.className}>
        <Navbar />
        <div className="flex flex-row w-full">
          <Aside />
          {children}
          <Aside />
        </div>
      </body>
    </html>
  );
}
